// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqTRVm_xwuov2_q52YT30O5wnmMC81Ncc',
    appId: '1:764377443759:web:1b393d3717d643975f535a',
    messagingSenderId: '764377443759',
    projectId: 'quick-coat',
    authDomain: 'quick-coat.firebaseapp.com',
    storageBucket: 'quick-coat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQeMoIeHlnWelJ25NnzzdoxMDBvJ6_l7c',
    appId: '1:764377443759:android:ffb855462e5bba3d5f535a',
    messagingSenderId: '764377443759',
    projectId: 'quick-coat',
    storageBucket: 'quick-coat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA75BjuCmXA9PGwvG1uTMYPMpQR1Viqup0',
    appId: '1:764377443759:ios:786db79743f77a495f535a',
    messagingSenderId: '764377443759',
    projectId: 'quick-coat',
    storageBucket: 'quick-coat.firebasestorage.app',
    iosBundleId: 'com.example.quickcoat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA75BjuCmXA9PGwvG1uTMYPMpQR1Viqup0',
    appId: '1:764377443759:ios:786db79743f77a495f535a',
    messagingSenderId: '764377443759',
    projectId: 'quick-coat',
    storageBucket: 'quick-coat.firebasestorage.app',
    iosBundleId: 'com.example.quickcoat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqTRVm_xwuov2_q52YT30O5wnmMC81Ncc',
    appId: '1:764377443759:web:a1d60f55ac3a2a9c5f535a',
    messagingSenderId: '764377443759',
    projectId: 'quick-coat',
    authDomain: 'quick-coat.firebaseapp.com',
    storageBucket: 'quick-coat.firebasestorage.app',
  );
}
